// This file contains Cloudinary URLs for static videos
// Auto-generated by upload-videos.ts script
// Do not edit manually. Run the upload script to regenerate.

export const STATIC_VIDEOS = {
  HERO_VIDEO: "https://res.cloudinary.com/dn7dezome/video/upload/v1764773232/yogreet-static/videos/hero-video.mov",
  SELLER_HERO: "https://res.cloudinary.com/dn7dezome/video/upload/v1764773248/yogreet-static/videos/seller-hero.mp4",
} as const;

// Export individual video URLs for convenience
export const HERO_VIDEO_URL = STATIC_VIDEOS.HERO_VIDEO;
export const SELLER_HERO_URL = STATIC_VIDEOS.SELLER_HERO;
