// This file is auto-generated by upload-static-images.ts
// Do not edit manually. Run the upload script to regenerate.

export const STATIC_IMAGES = {
  YOGREET_LOGO: "https://res.cloudinary.com/dn7dezome/image/upload/v1764603058/yogreet-static/Yogreet-logo.png",
  ASAFOETIDA_POWDER_SPICE: "https://res.cloudinary.com/dn7dezome/image/upload/v1764603060/yogreet-static/asafoetida-powder-spice.jpg",
  CARDAMOM_PODS_SPICE: "https://res.cloudinary.com/dn7dezome/image/upload/v1764603061/yogreet-static/cardamom-pods-spice.jpg",
  CLOVES_WHOLE_SPICE: "https://res.cloudinary.com/dn7dezome/image/upload/v1764603062/yogreet-static/cloves-whole-spice.jpg",
  CORIANDER_POWDER_SPICE: "https://res.cloudinary.com/dn7dezome/image/upload/v1764603063/yogreet-static/coriander-powder-spice.jpg",
  CUMIN_SEEDS_SPICE: "https://res.cloudinary.com/dn7dezome/image/upload/v1764603065/yogreet-static/cumin-seeds-spice.jpg",
  FENUGREEK_SEEDS_SPICE: "https://res.cloudinary.com/dn7dezome/image/upload/v1764603066/yogreet-static/fenugreek-seeds-spice.jpg",
  HEROSECTION: "https://res.cloudinary.com/dn7dezome/image/upload/v1764603073/yogreet-static/herosection.jpg",
  PLACEHOLDER_LOGO_PNG: "https://res.cloudinary.com/dn7dezome/image/upload/v1764603083/yogreet-static/placeholder-logo.png",
  PLACEHOLDER_LOGO_SVG: "https://res.cloudinary.com/dn7dezome/image/upload/v1764603083/yogreet-static/placeholder-logo.svg",
  PLACEHOLDER_USER: "https://res.cloudinary.com/dn7dezome/image/upload/v1764603085/yogreet-static/placeholder-user.jpg",
  PLACEHOLDER_JPG: "https://res.cloudinary.com/dn7dezome/image/upload/v1764603086/yogreet-static/placeholder.jpg",
  PLACEHOLDER_SVG: "https://res.cloudinary.com/dn7dezome/image/upload/v1764603086/yogreet-static/placeholder.svg",
  PROFESSIONAL_MAN_1: "https://res.cloudinary.com/dn7dezome/image/upload/v1764603087/yogreet-static/professional-man-1.jpg",
  PROFESSIONAL_MAN_2: "https://res.cloudinary.com/dn7dezome/image/upload/v1764603089/yogreet-static/professional-man-2.png",
  PROFESSIONAL_WOMAN_1: "https://res.cloudinary.com/dn7dezome/image/upload/v1764603091/yogreet-static/professional-woman-1.jpg",
  PROFESSIONAL_WOMAN_2: "https://res.cloudinary.com/dn7dezome/image/upload/v1764603092/yogreet-static/professional-woman-2.png",
  RED_CHILI_POWDER_SPICE: "https://res.cloudinary.com/dn7dezome/image/upload/v1764603095/yogreet-static/red-chili-powder-spice.jpg",
  TURMERIC_POWDER_SPICE: "https://res.cloudinary.com/dn7dezome/image/upload/v1764603099/yogreet-static/turmeric-powder-spice.jpg",
} as const;

// Helper to get image URL by original filename
export const getStaticImage = (filename: string): string => {
  const key = filename
    .replace(/.[^/.]+$/, "")
    .replace(/[^a-zA-Z0-9]/g, "_")
    .replace(/^([0-9])/, "_$1")
    .toUpperCase();
  
  return (STATIC_IMAGES as Record<string, string>)[key] || filename;
};

// Export individual image URLs for convenience
export const YOGREET_LOGO_URL = STATIC_IMAGES.YOGREET_LOGO;
export const ASAFOETIDA_POWDER_SPICE_URL = STATIC_IMAGES.ASAFOETIDA_POWDER_SPICE;
export const CARDAMOM_PODS_SPICE_URL = STATIC_IMAGES.CARDAMOM_PODS_SPICE;
export const CLOVES_WHOLE_SPICE_URL = STATIC_IMAGES.CLOVES_WHOLE_SPICE;
export const CORIANDER_POWDER_SPICE_URL = STATIC_IMAGES.CORIANDER_POWDER_SPICE;
export const CUMIN_SEEDS_SPICE_URL = STATIC_IMAGES.CUMIN_SEEDS_SPICE;
export const FENUGREEK_SEEDS_SPICE_URL = STATIC_IMAGES.FENUGREEK_SEEDS_SPICE;
export const HEROSECTION_URL = STATIC_IMAGES.HEROSECTION;
export const PLACEHOLDER_LOGO_PNG_URL = STATIC_IMAGES.PLACEHOLDER_LOGO_PNG;
export const PLACEHOLDER_LOGO_SVG_URL = STATIC_IMAGES.PLACEHOLDER_LOGO_SVG;
export const PLACEHOLDER_USER_URL = STATIC_IMAGES.PLACEHOLDER_USER;
export const PLACEHOLDER_JPG_URL = STATIC_IMAGES.PLACEHOLDER_JPG;
export const PLACEHOLDER_SVG_URL = STATIC_IMAGES.PLACEHOLDER_SVG;
export const PROFESSIONAL_MAN_1_URL = STATIC_IMAGES.PROFESSIONAL_MAN_1;
export const PROFESSIONAL_MAN_2_URL = STATIC_IMAGES.PROFESSIONAL_MAN_2;
export const PROFESSIONAL_WOMAN_1_URL = STATIC_IMAGES.PROFESSIONAL_WOMAN_1;
export const PROFESSIONAL_WOMAN_2_URL = STATIC_IMAGES.PROFESSIONAL_WOMAN_2;
export const RED_CHILI_POWDER_SPICE_URL = STATIC_IMAGES.RED_CHILI_POWDER_SPICE;
export const TURMERIC_POWDER_SPICE_URL = STATIC_IMAGES.TURMERIC_POWDER_SPICE;

// Convenience aliases for common placeholders
export const PLACEHOLDER_LOGO_URL = STATIC_IMAGES.PLACEHOLDER_LOGO_PNG;
export const PLACEHOLDER_URL = STATIC_IMAGES.PLACEHOLDER_SVG;
